### DISCUSSION TITLE
Cant create tags: `You're not authorized to create a tag`

### DISCUSSION THREAD

**Discussion by mrclrchtr** [actions/create-github-app-token#173] [Q&A] [answered]
Hi, I'm desperately trying to connect this action with the cycjimmy/semantic-release-action.

The following code:
```yaml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release
on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Dry Run
        default: false
        required: false
  push:
    branches:
      - main

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@cb425203a562475bca039ba4dbf90c7f9ac790f4 # v4.1.0
        with:
          dry_run: "${{ inputs.dry-run }}"
          semantic_version: 24.1.1
          extra_plugins: |
            - conventional-changelog-conventionalcommits@8.0.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
```

I have tried many different combinations (`persist-credentials: false`, order of commands etc.), but I always get the following error message:

```
remote: error: GH006: Protected tag update failed for refs/tags/v2.11.0.        
remote: 
remote: - You're not authorized to create a tag        
To https://github.com/hcloud-talos/terraform-hcloud-talos
 ! [remote rejected] v2.11.0 -> v2.11.0 (protected tag hook declined)
error: failed to push some refs to 'https://github.com/hcloud-talos/terraform-hcloud-talos'
remote: error: GH006: Protected tag update failed for refs/tags/v2.11.0.        
remote: 
remote: - You're not authorized to create a tag        
To https://github.com/hcloud-talos/terraform-hcloud-talos
 ! [remote rejected] v2.11.0 -> v2.11.0 (protected tag hook declined)
```

Can anyone please help?
