### DISCUSSION TITLE
Add support for multiple owner/org spaces

### DISCUSSION THREAD

**Discussion by erharb** [actions/create-github-app-token#83] [Ideas]
We're trying to use the create-github-app-token action in our enterprise GitHub cloud to create new repositories using our own GitHub Template repositories within a workflow running the gh CLI. The GitHub App being used has permissions to multiple "owner" spaces which we have setup (for example "internal/" and "product/", aka organizations), however the tokens currently created by the action only grant permissions to a single provided owner space.

This causes problems because we use an "internal" owner space to put the template repositories but would like to be able to create the repo using a template in a separate "product" owner space, however when creating a repository from a template you must have access to both spaces. It does work if we create the new repo in the same "internal" space as the template repository.

For example:
```yaml
    steps:
      - name: Create app access token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ vars.PROD_APP_ID }}"
          private-key: "${{ secrets.PROD_APP_PRIVATE_KEY }}"
          owner: "product"
```

```bash
...
+ gh repo create --private --clone --template internal/template-minimal product/my-minimal-repo
GraphQL: Could not resolve to a Repository with the name 'internal/template-minimal'. (repository)
Error: Process completed with exit code 1.
```

If I switch owner to "internal", then it won't have perms to the "product" space to create the new repository in. If we remove the "owner" param it only creates a token that can be used just for that repository, which means no permissions to create or load template repository.
```bash
owner and repositories not set, creating token for the current repository ("create-repo-from-template")
```

Could a new option be provided to input as a list of owner spaces instead of just one?
