### ISSUE TITLE
Retrieving the app's bot user no longer works

### ISSUE THREAD

**Issue by gastaldi** [actions/create-github-app-token#172]
The following instructions do not work anymore: 

- [Create a git committer string for an app installation
](https://github.com/actions/create-github-app-token#create-a-git-committer-string-for-an-app-installation)
- [Configure git CLI for an app's bot user](https://github.com/actions/create-github-app-token#configure-git-cli-for-an-apps-bot-user)

The following step fails: 
```yaml
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
```

Even https://api.github.com/users/dependabot[bot] returns 404, I wonder if something changed in GitHub that broke this behavior

**Comment by hypery2k** [comment]
did you installed your app in the org?
![image](https://github.com/user-attachments/assets/370f978a-27dd-433c-907d-287b4fd5b654)
There should be an install button in the middle of the screen.

Had the same error and installing resolved it for me

**Comment by infinisil** [comment]
I'm having the same problem and can confirm that the App is installed on the org.

Note that it doesn't actually fail the workflow, but rather just messes up the commits: https://github.com/NixOS/SC-election-2024/commit/f0ef6dfead7172602ff814e979f09574f4096ab1

In [the patch](https://github.com/NixOS/SC-election-2024/commit/f0ef6dfead7172602ff814e979f09574f4096ab1.patch) it shows as:

```
From: "nix-elections[bot]"
 <{
  "message":"Resource not accessible by integration",
  "documentation_url":"https://docs.github.com/rest",
  "status":"403"
 }+nix-elections[bot]@users.noreply.github.com>
```

Notably with the status code 403, rather than the 404 reported when running the corresponding command locally.

**Comment by StepanKuksenko** [comment]
I experience the same issue:
```
      - name: Get token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: "org-name"
          repositories: "repo-name"

      - name: Get user id
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
```

error:
```
gh: Resource not accessible by integration (HTTP 403)
```

The latest successful run was yesterday (Sep 16)
