### ISSUE TITLE
Support `repositories: ${{ github.repository }}`

### ISSUE THREAD

**Issue by MPV** [actions/create-github-app-token#185]
Could we please support passing (only) `${{ github.repository }}` to the `repositories` input?

**Comment by MPV** [comment]
I've had to make use of this ugly workaround for now:

```yaml
    steps:
      - name: Extract repo (only, not org) from ${{ github.repository }}
        id: repo
        run: |
          org_slash_repo="${{ github.repository }}"
          repo="${org_slash_repo##*/}"
          echo "repo=${repo}" >> "${GITHUB_OUTPUT}"
    
      - name: Create GitHub token for checking out ${{ github.repository }}
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: ${{ vars.MYORG_SOME_APP_ID }}
          private-key: ${{ secrets.MYORG_SOME_APP_PRIVATE_KEY }}
          owner: myorg
          repositories: ${{ steps.repo.outputs.repo }}
    
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ steps.app-token.outputs.token }}
```

But could we please add support for not needing it?

**Comment by MPV** [comment]
> I've had to make use of this ugly workaround for now:
> [...]
> But could we please add support for not needing it?

Because when trying without it, like this:

```yaml
    steps:
      - name: Create GitHub token for checking out ${{ github.repository }}
        uses: actions/create-github-app-token@5d869da34e18e7287c1daad50e0b8ea0f506ce69 # v1.11.0
        id: app-token
        with:
          app-id: ${{ vars.MYORG_SOME_APP_ID }}
          private-key: ${{ secrets.MYORG_SOME_APP_PRIVATE_KEY }}
          owner: myorg
          repositories: ${{ github.repository }}

      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          token: ${{ steps.app-token.outputs.token }}
```

I only get errors like this:
```js
Failed to create token for "myorg/example-prototype-api" (attempt 2): Not Found - https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app
Failed to create token for "myorg/example-prototype-api" (attempt 3): Not Found - https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app
Failed to create token for "myorg/example-prototype-api" (attempt 4): Not Found - https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app
RequestError [HttpError]: Not Found - https://docs.github.com/rest/apps/apps#get-a-repository-installation-for-the-authenticated-app
    at fetchWrapper (/home/runner/_work/_actions/actions/create-github-app-token/5d869da34e18e7287c1daad50e0b8ea0f506ce69/dist/main.cjs:37109:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async hook4 (/home/runner/_work/_actions/actions/create-github-app-token/5d869da34e[18](https://github.com/myorg/example-prototype-api/actions/runs/11816114724/job/32918724422?pr=73#step:2:18)e7287c1daad50e0b8ea0f506ce69/dist/main.cjs:39476:18)
    at async getTokenFromRepository (/home/runner/_work/_actions/actions/create-github-app-token/5d869da34e18e7287c1daad50e0b8ea0f506ce69/dist/main.cjs:39792:20)
    at async RetryOperation._fn (/home/runner/_work/_actions/actions/create-github-app-token/5d869da34e18e7287c1daad50e0b8ea0f506ce69/dist/main.cjs:39667:24) {
  status: 404,
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/myorg/myorg%2Fexample-prototype-api/installation',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/create-github-app-token',
      authorization: 'bearer [REDACTED]'
    },
    request: { hook: [Function: bound hook4] AsyncFunction }
  },
```

(note the duplicated `myorg` there in `myorg/myorg/example-prototype-api`)

**Comment by MPV** [comment]
This is especially interesting/needed nowadays when there is "Ruleset Workflows", which seem to require making use of `actions/create-github-app-token` since the `GITHUB_TOKEN` they use don't appear to have access to other repositories than the one the workflow is defined in (?).

**Comment by Yang-33** [comment]
I think
```yaml
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ github.event.repository.name }}
```
works, if you want to issue token only for `${{ github.repository }}`.
