### ISSUE TITLE
Missing `appId` option

### ISSUE THREAD

**Issue by ArquintL** [actions/create-github-app-token#249]
I'm trying to update from `v1` to `v2` but get the following error that seems to indicate that the `app-id` option is not correctly forwarded to Octokit's auth-app:
```
Error: [@octokit/auth-app] appId option is required
    at createAppAuth (/home/runner/work/_actions/actions/create-github-app-token/v2/dist/main.cjs:42355:11)
    at main (/home/runner/work/_actions/actions/create-github-app-token/v2/dist/main.cjs:42560:17)
    at Object.<anonymous> (/home/runner/work/_actions/actions/create-github-app-token/v2/dist/main.cjs:42684:20)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    at node:internal/main/run_main_module:28:49
```

I'm successfully using this action in `v1` as follows:
```
- name: Get token from GitHub App
   uses: actions/create-github-app-token@v1
   id: app_token
   with:
     app-id: ${{ secrets.APP_ID }}
     private-key: ${{ secrets.APP_PEM }}
     owner: ${{ github.repository_owner }}
     repositories: "<omitted, comma-separated list of repos>"
```

**Comment by gr2m** [comment]
In the same action, without changing anything else, does it fail if you change `@v1` to `@v2`?

I'm using the v2 a lot myself and didn't run into this problem. It's most likely something else. Maybe `secrets.APP_ID` should be `vars.APP_ID` or the secret is no longer set where you get the error?

**Comment by ArquintL** [comment]
`v1` works flawlessly but when changing the tag to `v2`, the error mentioned above occurs

**Comment by dptaf** [comment]
seeing the same thing on v2

**Comment by gr2m** [comment]
If someone could create minimal workflow that reproduces the bug, it would help greatly to figure out the source of the bug.

**Comment by till** [comment]
I think this problem stems from the secret being empty. E.g. the repository may not have access to it in that situation.

My situation was the following: I have this `actions/create-github-app-token` in a workflow that I called from another repository — because I assumed the workflow would still be able to access my (org) secrets.

This is not the case, so I had define the secrets as parameters to the workflow and call it like this:

```yaml
jobs:
  lint:
    uses: my-org/workflows/.github/workflows/lint.yml@main
    secrets:
      app-id: ${{ secrets.MY_APP_ID_SECRET }}
      private-key: ${{ secrets.MY_APP_PRIVATE_KEY }}
```

Then in the workflow, I use `${{ secrets.app-id }}` etc..

Maybe the error could be improved and say that the appId is empty, or something?

**Comment by ArquintL** [comment]
Thanks for the pointer! I think that's exactly the problem. I've observed the issue in a PR created by Dependabot and I guess the corresponding CI run (on push) does not have access to the secrets

**Comment by till** [comment]
@ArquintL If it's dependabot, then you need dependabot secrets, or something. Or skip it all together.

**Comment by Mqxx** [comment]
If you "sub-call" a workflow that uses secrets you need to pass the `secrets: inherit` option.

Otherwise the secrets will be empty and then you get the error.

```yml
name: 'Reset'

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: 'Branch to reset'
        required: true

  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'Branch to reset'
        options:
          - 'generated'
        required: true
  
jobs:
  resetting-branch:
    name: 'Resetting branch'
    secrets: inherit # <-- Important!
    uses: './.github/workflows/reset_branch.yml' # <-- This workflow uses 'actions/create-github-app-token'
    with:
      branch: ${{ github.event.inputs.branch }}
```

**Comment by rcghpge** [comment]
Can there be an added validation feature or something with an example provided above. I’m not sure if organizations who are automating or building their own software are ok with their technology wrapped in quotes as seen here.

`v1` example
```yaml
- name: Get token from GitHub App
   uses: actions/create-github-app-token@v1
   id: app_token
   with:
     app-id: ${{ secrets.APP_ID }}
     private-key: ${{ secrets.APP_PEM }}
     owner: ${{ github.repository_owner }}
     repositories: "<omitted, comma-separated list of repos>"
```

![Image](https://github.com/user-attachments/assets/79080f67-93c1-4881-9531-cc8a9e3a5745)
