### ISSUE TITLE
Support tokens with access to custom repositories and user/organization accounts

### ISSUE THREAD

**Issue by parkerbxyz** [actions/create-github-app-token#4]
The use cases we want to cover is

1. By default, create a token scoped to the current repository
2. Allow to scope to a set of repositories by names for the current owner
3. Allow to scope to a different owner (all installation repositories)
4. Allow to scope to a set of repositories by names for a different owner

Our API idea is

```yml
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app_id: ${{ vars.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          owner: some-owner
          repositories: some-repo1,some-repo2
```

Both `owner` and `repositories` would be optional, and one can be set to the other. `owner` defaults to the current repository owner, and repositories defaults to the current repository name.

**Comment by kmaehashi** [comment]
Under the GitHub Enterprise Cloud setup, we are often required to access repositories under multiple organizations. It would be great if you consider covering the checkout use case like these:

```yaml
# Checkout orgA/repoA and orgB/repoB

- uses: actions/create-github-app-token@v1
  id: app-token
  with:
    app_id: ${{ vars.APP_ID }}
    private_key: ${{ secrets.PRIVATE_KEY }}
    repositories: orgA/repoA, orgB/repoB

- uses: actions/checkout@v4
  with:
    repository: 'orgA/repoA'
    token: ${{ steps.app-token.outputs.token }}

- uses: actions/checkout@v4
  with:
    repository: 'orgB/repoB'
    token: ${{ steps.app-token.outputs.token }}
```


```yaml
# Checkout the current repository which has orgA/repoA and orgB/repoB as submodule

- uses: actions/create-github-app-token@v1
  id: app-token
  with:
    app_id: ${{ vars.APP_ID }}
    private_key: ${{ secrets.PRIVATE_KEY }}
    repositories: ${{ github.repository}}, orgA/repoA, orgB/repoB

- uses: actions/checkout@v4
  with:
    submodules: true
    token: ${{ steps.app-token.outputs.token }}
```
