### ISSUE TITLE
Add support for retries

### ISSUE THREAD

**Issue by Moser-ss** [actions/create-github-app-token#71]
This issue comes from this issue  https://github.com/actions/create-github-app-token/issues/42#issuecomment-1783965170
----
As a rule of thumb, in all code that works with the network, the network will always one day fail. 
For that reason, it will be great to implement a retry logic inside of the action so that the requests made to the GitHub API have a retry logic. 

Also, we can expose the retry parameters to the user.
```
  attempt_limit:
    description: Number of attempts
    required: false
    default: 2
  attempt_delay:
    description: A delay between attempts in ms
    required: false
    default: 0
```
