### ISSUE TITLE
[FEAT]: Support overriding github api url

### ISSUE THREAD

**Issue by gr2m** [actions/create-github-app-token#77]
originally posted by @harshtrivedi134 at https://github.com/octokit/octokit.js/issues/2569

### Describe the need

Reference from [discussion](https://github.com/octokit/octokit.js/discussions/2566#discussioncomment-7483549)
I was creating an access token for a github app installed in a different organization and repository. I learned about https://github.com/actions/create-github-app-token#create-a-token-for-all-repositories-in-another-owners-installation. 

Similar to the `baseUrl` option in [Octokit constructor](https://github.com/octokit/octokit.js/discussions/2566#discussioncomment-7483549), it would be great if we could specify the github API url as an input to this action

```
      - uses: actions/create-github-app-token@v1
        id: get-access-token
        with:
          app-id: APP_ID
          private-key: PRIVATE_KEY
          base-url: https://slack-github.com/api/
```

I tried creating an access token for my github app installed in a different organization by specifying the owner and repository using the following:

```
      - uses: actions/create-github-app-token@v1
        id: get-access-token
        with:
          app-id: APP_ID
          private-key: PRIVATE_KEY
          owner: "owner"
          repositories: |
            owner/repo_name
```
However, the default github API hostname/url is set to `api.github.com` and we cannot change it to a custom hosted github installation. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
